name: Laravel CI/CD

on:
  push:
    branches: [main, develop]


jobs:
  deploy:
    name: Deploy to Server via SSH
    runs-on: ubuntu-22.04
    environment: ${{ github.ref_name == 'develop' && 'development' || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_PEM }}
          port: ${{ secrets.SSH_PORT }}
          source: "./biblioteca/."
          target: "${{ vars.DEPLOY_BASE_PATH }}/${{ vars.DEPLOY_FOLDER }}"

      - name: Upload .env from variable
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_PEM }}
          port: ${{ secrets.SSH_PORT }}
          script: |
                  base_path=${{ vars.DEPLOY_BASE_PATH }}
                  folder=${{ vars.DEPLOY_FOLDER }}
                  config_folder=${{ vars.ENV_FOLDER }}
                  echo "${base_path}/${config_folder}/.env"
                  echo "${base_path}/${folder}/.env"
                  cp -r "${base_path}/${config_folder}/.env" "${base_path}/${folder}/.env"


      - name: Run remote commands
        uses: appleboy/ssh-action@v1.2.1
        env:
            BASE_PATH: /var/www/html
            FOLDER: biblioteca
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_PEM }}
          port: ${{ secrets.SSH_PORT }}
          script: |
                  base_path=${{ vars.DEPLOY_BASE_PATH }}
                  folder=${{ vars.DEPLOY_FOLDER }}
                  echo "$base_path/$folder"
                  cd "$base_path/$folder"

                  composer install --no-interaction --prefer-dist --optimize-autoloader
                  php artisan migrate --force
                  php artisan config:cache
                  php artisan route:cache
                  php artisan view:cache
                  nohup php artisan serve --port 8080 > /dev/null 2>&1 & disown
                  sudo systemctl restart nginx

      - name: Rename remote folder
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_PEM }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            base_path=${{ vars.DEPLOY_BASE_PATH }}
            folder=${{ vars.DEPLOY_FOLDER }}
            echo "$base_path/$folder"
            cd "$base_path/$folder"

            mv ./biblioteca/* .