name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server via SSH
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_PEM }}
          port: ${{ secrets.SSH_PORT }}
          source: "./${{ vars.DEPLOY_FOLDER }}/*"
          target: "${{ vars.DEPLOY_BASE_PATH }}"

      - name: Upload .env from variable
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_PEM }}
          port: ${{ secrets.SSH_PORT }}
          base_path: ${{ vars.DEPLOY_BASE_PATH }}
          folder: ${{ vars.DEPLOY_FOLDER }}
          config_folder: ${{ vars.CONFIG_FOLDER }}
          script: |
            cp "$config_path/$config_folder/.env.production" "$base_path/$folder/.env"


      - name: Run remote commands
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_PEM }}
          port: ${{ secrets.SSH_PORT }}
          base_path: ${{ vars.DEPLOY_BASE_PATH }}
          folder: ${{ vars.DEPLOY_FOLDER }}
          script: |
            cd "$base_path/$folder"
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            nohup php artisan serve --port 8000 > /dev/null 2>&1 & disown
            sudo systemctl restart nginx
